Temp deletion
git-flash/FLASH pull request #125
Opened 2021-04-07 17:09 UTC by sumedhtadimeti

2021-04-07 20:10 UTC, Buzzec commented
Is this ready for review? If not make it a draft.

2021-04-07 20:28 UTC, sumedhtadimeti commented
> Is this ready for review? If not make it a draft.
it's ready for review

2021-04-07 20:35 UTC, Buzzec requested changes

2021-04-07 20:35 UTC, Buzzec commented on app/models/user.rb
> +  # hides the user instead of destroying the user
Dangling comment

2021-04-07 20:35 UTC, Buzzec commented on config/routes.rb
> +  # resources :users
Remove this

2021-04-09 21:19 UTC, Buzzec approved these changes

2021-04-10 03:06 UTC, Luke2v52 requested changes
Do not merge with master

2021-04-10 03:35 UTC, Luke2v52 requested changes

2021-04-10 03:35 UTC, Luke2v52 commented on app/views/layouts/_nav_bar.html.erb
> -            </div>
You removed the closing div

2021-04-10 19:58 UTC, Luke2v52 approved these changes
I fixed the issues

2021-04-10 20:00 UTC, merged